// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef resource_h
#define resource_h
#include <FL/Fl.H>

class GResource {
public:
  static unsigned char Btn_Circle_Gray[3526];
  static unsigned char Btn_Circle_Green[2569];
  static unsigned char Btn_Circle_Green_Selected[5045];
  static unsigned char Btn_Circle_Red[2577];
  static unsigned char Btn_Circle_Red_Selected[4908];
  static unsigned char Btn_FrontColor[537];
  static unsigned char Btn_Gray[3803];
  static unsigned char Btn_Green[2887];
  static unsigned char Btn_Green_Selected[5457];
  static unsigned char Guage_left[54375];
  static unsigned char Background[7708];
};
#endif
