// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef CMainWindow_h
#define CMainWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Pack.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Scroll.H>
#include <FL/Fl_Dial.H>

/**
 comments
*/
class UserInterface : :windo{} {
public:
  void make_window();
// my comment
private:
  int x; 
};
#endif
