// generated by Fast Light User Interface Designer (fluid) version 1.0305

#include "CMainWindow.h"

void UserInterface::make_window() {
  Fl_Double_Window* w;
// my comment
  printf("Hello, World!\n");
  { Fl_Double_Window* o = new Fl_Double_Window(275, 140);
    w = o; if (w) {/* empty */}
    o->user_data((void*)(this));
    { Fl_Pack* o = new Fl_Pack(25, 25, 250, 115, "Lable");
      { new Fl_Button(50, 50, 25, 25, "Button");
      } // Fl_Button* o
      { new Fl_Slider(75, 50, 25, 25, "ddfd");
      } // Fl_Slider* o
      { Fl_Scroll* o = new Fl_Scroll(50, 50, 225, 90);
        { new Fl_Dial(75, 75, 25, 25, "ddsd");
        } // Fl_Dial* o
        o->end();
      } // Fl_Scroll* o
      o->end();
    } // Fl_Pack* o
    o->end();
  } // Fl_Double_Window* o
}
#if 1
#endif
