// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef CButton_Custom_h
#define CButton_Custom_h
#include <FL/Fl.H>
#include <FL/Fl_Group.H>
extern void butt_cb(Fl_Group*, void*);

class CMyButton : public Fl_Group {
public:
  CMyButton(int X, int Y, int W, int H, const char *L = 0);
  CMyButton();
  void butt_cb(Fl_Widget *butt, void *data);
  void draw();
};
#endif
