// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef CMainScreen_h
#define CMainScreen_h
#include <FL/Fl.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Pack.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>

class MainScreen : public Fl_Group {
public:
  MainScreen(int X, int Y, int W, int H, const char *L = 0);
  //void draw();
};
#endif
