// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef CSettingScreen_h
#define CSettingScreen_h
#include <FL/Fl.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>

class CSettingScreen : public Fl_Group {
public:
  CSettingScreen(int X, int Y, int W, int H, const char *L = 0);
};
#endif
